export async function GET() {
    const tickets = [
        {
            id: 't-001',
            title: 'Cannot access email',
            description: 'User is unable to access their email account.',
            priority: 'High',
            status: 'Open',
            assignee: 'Unassigned',
            updatedAt: '2025-11-48T10:15:00Z',
        },
        {
            id: 't-002',
            title: 'Software installation request',
            description: 'Request to install new software on workstation.',
            priority: 'Medium',
            status: 'In Progress',
            assignee: 'Alice@help.com',
            updatedAt: '2025-11-47T14:30:00Z',
        },
        {
            id: 't-003',
            title: 'Network connectivity issue',
            description: 'Intermittent network connectivity in the office.',
            priority: 'Critical',
            status: 'On Hold',
            assignee: 'Unassigned',
            updatedAt: '2025-11-46T09:45:00Z',
        },
        {
            id: 't-004',
            title: 'Password reset needed',
            description: 'User forgot their password and needs a reset.',
            priority: 'Low',
            status: 'Resolved',
            assignee: 'sam@help.com',
            updatedAt: '2025-11-45T11:20:00Z',
        },
        {
            id: 't-005',
            title: 'Printer not working',
            description: 'Office printer is jammed and not printing documents.',
            priority: 'Medium',
            status: 'Open',
            assignee: 'jake@help.com',
            updatedAt: '2025-11-44T16:10:00Z',
        },
        {
            id: 't-006',
            title: 'Computer running slow',
            description: 'User reports that their computer is running very slowly.',
            priority: 'High',
            status: 'In Progress',
            assignee: 'Unassigned',
            updatedAt: '2025-11-43T13:55:00Z',
        },
        {
            id: 't-007',
            title: 'VPN connection issues',
            description: 'User cannot connect to the VPN from home.',
            priority: 'Critical',
            status: 'Open',
            assignee: 'jane@help.com',
            updatedAt: '2025-11-42T08:25:00Z',
        },
        {
            id: 't-008',
            title: 'Email spam problem',
            description: 'User is receiving a large amount of spam emails.',
            priority: 'Low',
            status: 'Resolved',
            assignee: 'peter@help.com',
            updatedAt: '2025-11-41T12:40:00Z',
        },
        {
            id: 't-009',
            title: 'Software bug report',
            description: 'User reports a bug in the accounting software.',
            priority: 'Medium',
            status: 'On Hold',
            assignee: 'Unassigned',
            updatedAt: '2025-11-40T15:35:00Z',
        },
        {
            id: 't-010',
            title: 'Hardware upgrade request',
            description: 'Request to upgrade RAM on workstation.',
            priority: 'Low',
            status: 'In Progress',
            assignee: 'smith@help.com',
            updatedAt: '2025-11-39T10:05:00Z',
        },
        {
            id: 't-011',
            title: 'Data backup failure',
            description: 'Automated data backup is failing every night.',
            priority: 'High',
            status: 'Open',
            assignee: 'Unassigned',
            updatedAt: '2025-11-38T09:15:00Z',
        },
        {
            id: 't-012',
            title: 'Account locked out',
            description: 'User account is locked after multiple failed login attempts.',
            priority: 'Critical',
            status: 'Resolved',
            assignee: 'kiefer@help.com',
            updatedAt: '2025-11-37T14:50:00Z',
        },
        {
            id: 't-013',
            title: 'Monitor not displaying',
            description: 'User reports that their monitor is not displaying anything.',
            priority: 'Medium',
            status: 'In Progress',
            assignee: 'Unassigned',
            updatedAt: '2025-11-36T11:30:00Z',
        },
        {
            id: 't-014',
            title: 'Keyboard malfunction',
            description: 'User\'s keyboard is not responding properly.',
            priority: 'Low',
            status: 'Open',
            assignee: 'Unassigned',
            updatedAt: '2025-11-35T13:20:00Z',
        }
    ];
    return Response.json(tickets);
}
        